swagger: "2.0"
basePath: "osori.team-penthouse.com/"
host : "osori.team-penthouse.com/"
servers:
    - description: Base Url
      url: https://team-penthouse.com/
info:
    version : "1.0.0"
    title : ""
paths:
    $ref : './paths/paths.yaml'
definitions:
    $ref : './definitions/definitions.yaml'