swagger: "2.0"
basePath: "localhost:3000"
host : "localhost:3000"
servers:
    - description: Base Url
      url: localhost:3000
info:
    version : "1.0.0"
    title : ""
paths:
    $ref : './paths/paths.yaml'
definitions:
    $ref : './definitions/definitions.yaml'